<html>
    <head>
        <meta charset="utf-8"/>
        <title>GitHub Stars</title>
    </head>
    <body>
        <app></app>
        <!--table style="border:1px;width:100%">
            <tr>
                <th>Name</th>
                <th>StyleCI</th>
                <th>Travis</th>
                <th>Scrutinizer</th>
                <th>Scrutinizer</th>
                <th>Code Climate</th>
                <th>Code Climate</th>
                <th>Is it maintained</th>
                <th>Is it maintained</th>
                </tr>

            <?php //$repos = array_slice($repos, 0, 10); ?>
            <?php //foreach($repos as $repName => $rep): ?>
            <tr>
                <td>'.$repName.'</td>
                <td><img src="https://styleci.io/repos/'.$rep->id.'/shield"/></td>
                <td><img src="https://img.shields.io/travis/'.$rep->full_name.'/master.svg?style=flat-square"/></td>
                <td><img src="https://img.shields.io/scrutinizer/coverage/g/'.$rep->full_name.'.svg?style=flat-square"/></td>
                <td><img src="https://img.shields.io/scrutinizer/g/'.$rep->full_name.'.svg?style=flat-square"/></td>
                <td><img src="https://codeclimate.com/github/'.$rep->full_name.'/badges/gpa.svg"/></td>
                <td><img src="https://codeclimate.com/github/'.$rep->full_name.'/badges/coverage.svg"/></td>
                <td><img src="http://isitmaintained.com/badge/resolution/'.$rep->full_name.'.svg"/></td>
                <td><img src="http://isitmaintained.com/badge/open/'.$rep->full_name.'.svg"/></td>

                </tr>
            <?php //endforeach; ?>
            </table-->

        <script src="/assets/app.js"></script>
        <link rel="stylesheet" href='/assets/app.css'/>
        <!--script src="http://localhost:8080/assets/app.js"></script-->
        <!--script src="http://localhost:8080/webpack-dev-server.js"></script-->
    </body>
</html>
